name: "fcp-back-end-media"
services:
    media-db:
        build:
            context: ../DB
            dockerfile: ../dev-ops/dockerfiles/media-db
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../DB/data:/var/lib/mysql:rw
            - ../LOGS/media-db-logs:/var/log/mysql:rw
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD"]
            start_period: 3s
            interval: 1s
            timeout: 1s
            retries: 1000
    media-app:
        build: 
            context: ../MEDIA
            dockerfile: ../dev-ops/dockerfiles/media-app
        environment:
            - DB_HOST=:)
            - DB_PORT=:)
        depends_on:
            media-db:
                condition: service_healthy
